### ISSUE TITLE
database Qs

### ISSUE THREAD

**Issue by dansinker** [sinker/trumppoopwatch.org#1]
so right now there's a basic YML data layer. it's very readable & minimalist. however, it is a very manual update. and, it's currently only to his last known trump hotel visit. so a few questions:

1) what's an easy-to-update method of keeping a database across a few collaborators. Maybe it's this. maybe it's dumping the jekyll data layer and going google doc. I dunno. open to suggestions.

2) that dude with a mustache who works for NBC seems to keep the most complete record of trump visits via his twitter. spelunking that for an actual date & location database for everything is probably doable do we want to create the definitive database for trump location visits?

**Comment by waldoj** [comment]
Google Sheets is a slow and unreliable storage medium for a website. It's totally a doable thing, but it's rough. Best to start keeping it in YAML or JSON, and grow into Google Sheets as need be.

**Comment by waldoj** [comment]
Mark Knoller is _the_ guy for presidential data about random shit. He's a savant for records. Like, presidential libraries go to _him_ to find out when their guy did what, how many times he did it, etc. Knoller doesn't even have to check, he just _knows._

**Comment by tsaylor** [comment]
If you wanted to avoid all the work of a full blown database, you could use an off the shelf tool to put  data in an RSS feed (a wordpress.com blog for example) and either fetch that data in javascript to render the page, or schedule a task that pulls the rss down, updates the markdown source, and rebuilds/republishes the site. That keeps the interface for updating the data really familiar and reliable, and doesn't require much more infrastructure (none for the JS option, any VPS or home server for the scheduled rebuild option).

**Comment by dansinker** [comment]
whoa that is cray. 

I have started another database discussion in #8 which is about how to best get the historical information. However, these are interrelated conversations since, as we build out the DB, making it useful & accessible outside the poopwatch seems important and thusly may influence the actual db design.

I fully expect that we won't hang around YAML for long.

**Comment by tsaylor** [comment]
Yeah, if the dataset itself is a product then you don't want that duct tape solution I described.

**Comment by dansinker** [comment]
I think all the database action is in #8 right now and at least for now we'll stick with YAML
