### ISSUE TITLE
github pages all fucked up

### ISSUE THREAD

**Issue by dansinker** [sinker/trumppoopwatch.org#4]
github hates the plugin & CSS stuff so I gotta sort that out. 

That said it is serving a hot piece of garbage here: https://sinker.github.io/trumppoopwatch.org/

**Comment by waldoj** [comment]
What is even happening with the SCSS? You've got triple dashes in the front matter and everything. Huh.

**Comment by waldoj** [comment]
Suggestion—just compile the SCSS to CSS locally for now, and check it into the repo. Figure out the problem later.

**Comment by dansinker** [comment]
Yeah, Jekyll got too cute by a bunch lately and now everything is SASS instead of CSS which would be fine if I bothered to take the time to learn it but yeah that's not gonna happen.

All works fine locally, but github is not a fan.

**Comment by dansinker** [comment]
I decided to abort on gh-pages because it won't support the timeago plug-in. So have switched to S3 where it is now working fine at: http://www.trumppoopwatch.org.s3-website-us-east-1.amazonaws.com/

**Comment by dansinker** [comment]
so, closing.
