### ISSUE TITLE
Relative dates

### ISSUE THREAD

**Issue by dansinker** [sinker/trumppoopwatch.org#5]
So the main action for the sentence for how long it's been since Trump pooped is via the jekyll-timeago plug in.

And it works great except I'd rather it compute only by days not week+day

I.e. I'd rather it say "8 days" instad of "1 week and 1 day"

**Comment by waldoj** [comment]
Jekyll-Timeago doesn't support that, unfortunately. You can only customize the vagueness—`1 year ago` vs. `1 year and 1 month ago` vs. `year, 1 month, 3 weeks, and 5 days ago`.

**Comment by dansinker** [comment]
yeah, I'd love the measurement in days instead of weeks + days but perfect is the enemy of done so
