### ISSUE TITLE
build out the historical poop record

### ISSUE THREAD

**Issue by dansinker** [sinker/trumppoopwatch.org#8]
as referenced in #1 and #3, right now the first poop date is the Nov 4 visit to Hawaii (plus a test poop). There's extensive visits to other trump properties in the past that would be good to eventually have represented in the database (and then accessible via a historical poop list page). 

There's no outward-facing database of previous trump property visits, so if we can build this out it's actually useful beyond pooping. However, they've been fairly squirrley about these visits so there's no official source either. 

Kyle Griffin on Twitter has been documenting visits for a while, but I don't believe has been doing them from day one. At a certainly point, it'll require digging through news reports etc. However, scraping his Twitter is probably a good start since he [seems to follow a pretty standard format for these tweets](https://twitter.com/kylegriffin1/status/916668506510430209?lang=en)

**Comment by iandees** [comment]
FactBase has a calendar of his schedule in a couple easily-digestible formats: https://factba.se/topic/calendar

**Comment by dansinker** [comment]
WAAAAAAAAAAT

**Comment by dansinker** [comment]
so @iandees I haven't looked into FactBase beyond marveling that it exists, but how would we go about exporting & populating the YAML? with #11 I feel like the DB has the info necessary at this point to start htinking about how to do the historical poop record.

**Comment by dansinker** [comment]
building out an archive in https://github.com/sinker/trumppoopwatch.org/tree/pooparchive

however, I could only download to mid-October in Factbase (and then convert semi-manually to YML)

**Comment by dansinker** [comment]
continuing to build out the archive, mostly using Phillip Bump's infographic: https://img.washingtonpost.com/wp-apps/imrs.php?src=https://img.washingtonpost.com/news/politics/wp-content/uploads/sites/11/2017/11/Trump-Properties-1.jpg&w=1484

Which is about as fun as it sounds.

**Comment by iandees** [comment]
I just got back from Amsterdam but will lend a hand tomorrow morning. Let me know where I can jump in.

**Comment by dansinker** [comment]
I guess main thing would be if you can figure out a way to export the whole archive from Factbase. I've plugged around a bit but the quicklinks are just for the last 45 days or something like that. Not sure if there's a full archive somewhere. From there it's pretty easy since almost all his places have the name "Trump" in them, to extract only those entities (all non-property-based listings never refer to him as anything but "the President" which is helpful). That would get us a good way. Then mapping from CSV to YAML is pretty straightforward with some online tools.

**Comment by dansinker** [comment]
Fuck it, at this point I've got a good rhythm going. Here's how it works: 
1) Check a date on Phillip Bump's WaPo calendar, which as a basic starting point is useful but doesn't distinguish between the various Florida golf courses, or the difference between his hotel in DC or golf course in Virginia: https://img.washingtonpost.com/wp-apps/imrs.php?src=https://img.washingtonpost.com/news/politics/wp-content/uploads/sites/11/2017/11/Trump-Properties-1.jpg&w=1484
2) Look up the date on Factbase's calendar, which tends to back up the date on the Bump cal with additional information: https://factba.se/topic/calendar
3) In the case of discrepancies, do some google searching until I can sort out where he actually was
4) Attempt, when feeling up for it, to flesh out a better link than one of those two original sources since neither allow deep-linking to the actual day.

**Comment by dansinker** [comment]
I'm up to April 1 now. 

Joke is on me.

**Comment by dansinker** [comment]
I actually really do want better links for every visit, but that's going to be a new issue once the whole db is fleshed.

**Comment by dansinker** [comment]
and with 924c78f7ed7b6ad245df6ac1f1a6a69a0962a0a6 following the methodology above, _all_ trump property visits listed in Phillip Bump's calendar *and* Factbase are now in the database. Am going to close this issue & open one specific to fleshing out the link depth.
